In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
# Check for missing values
df.isna().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
# Show duplicated rows
df[df.duplicated(keep=False)]

     sepal_length  sepal_width  petal_length  petal_width    species
9             4.9          3.1           1.5          0.1     setosa
34            4.9          3.1           1.5          0.1     setosa
37            4.9          3.1           1.5          0.1     setosa
101           5.8          2.7           5.1          1.9  virginica
142           5.8          2.7           5.1          1.9  virginica

In [5]:
# Remove duplicates
df.drop_duplicates(subset=None, keep='first', inplace=True)

In [6]:
# Ensure duplicates are removed
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

In [ ]:
# Clean 'species' column by stripping whitespace and converting to lowercase
df['species'] = df['species'].str.strip().str.lower()